# Generated by Django 3.2.12 on 2022-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=20)),
            ],
        ),
    ]
